import { NextRequest, NextResponse } from "next/server";
import { kvGet } from "@/lib/kv";
import { TemplateRequest } from "@/lib/types";
import { buildTemplateHtml } from "@/lib/template-generator";
import archiver from "archiver";
import { PassThrough } from "stream";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const { token } = await params;

  // Look up request ID by token
  const requestId = await kvGet<string>(`token:${token}`);
  if (!requestId) {
    return new NextResponse("Not found", { status: 404 });
  }

  const request = await kvGet<TemplateRequest>(`request:${requestId}`);
  if (!request || request.downloadToken !== token) {
    return new NextResponse("Not found", { status: 404 });
  }

  // Build the HTML template
  const html = buildTemplateHtml(request);

  // Stream a ZIP
  const passThrough = new PassThrough();
  const archive = archiver("zip", { zlib: { level: 9 } });

  archive.pipe(passThrough);

  archive.append(html, { name: "index.html" });

  const setupGuide = buildSetupGuide(request);
  archive.append(setupGuide, { name: "SETUP.md" });

  await archive.finalize();

  const chunks: Buffer[] = [];
  for await (const chunk of passThrough) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  const zipBuffer = Buffer.concat(chunks);

  const filename = `${request.businessName.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-template.zip`;

  return new NextResponse(zipBuffer, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}

function buildSetupGuide(req: TemplateRequest): string {
  return `# ${req.businessName} — Website Template Setup Guide

## Getting Started

1. **Extract the ZIP** — Unzip the downloaded file to a folder on your computer.
2. **Open index.html** — Open this file in your browser to preview the site.
3. **Customise content** — Open \`index.html\` in a text editor (e.g., VS Code) and update:
   - Business name and tagline
   - Phone number, email, and address
   - Service descriptions
   - Images (replace placeholder \`src\` attributes with your own image paths)
4. **Upload to hosting** — Copy all files to your web hosting via FTP or your host's file manager.
5. **Point your domain** — Update DNS to point to your hosted files.

## Pages Included

${req.pages.map((p) => `- ${p}`).join("\n")}

## Customisation Tips

- The colour theme is set using CSS custom properties at the top of the \`<style>\` block.
- Fonts are loaded from Google Fonts — update the \`<link>\` tag to change fonts.
- All sections are clearly labelled with HTML comments for easy navigation.

## Need Help?

Email us at hello@webtemp.dev and we'll be happy to assist.

---
Generated by WebTemp · webtemp.vercel.app
`;
}
